### ISSUE TITLE
I don't know how to use cmake

### ISSUE THREAD

**Issue by Leodinas** [Sphereserver/Source2#1]
okay Research to understand the

**Comment by DarkLotus** [comment]
An exe is an exe no matter what it was built with. you run it the same as you would any other program, generally a double click is enough to do it.

If your using Cmake to build then you dont need to have anything to do with Visual studio or its SLN files.

**Comment by cbnolok** [comment]
Cmake is used to generate makefiles and/or projects for the IDEs (like visual studio), thorugh which you can compile sphere and generate the exe
