### ISSUE TITLE
Creating new char

### ISSUE THREAD

**Issue by azmanomer** [Sphereserver/Source2#2]
When u creating new char some starting items not placing correctly and after save console removing them. For example if u give 1000gp to chars they take 999gp and 1gp not placing world and after save server removing them. I tried it with fresh install.

**Comment by cbnolok** [comment]
Maybe it's a bit late, but... is this still happening, with latest commit? :D

**Comment by Kaylala** [comment]
Not too sure. Haven't heard from anyone in a long time tbh. Tried contacting a few a couple months back to see what was going on or what was needed and there weren't any replies.

**Comment by cbnolok** [comment]
I think this was fixed some commits ago. Feel free to reopen the issue if this isn't the case.
