### ISSUE TITLE
Crash: Vendor Sell

### ISSUE THREAD

**Issue by Tolokio** [Sphereserver/Source2#4]
When sell dialog show ups, few second later server crash.
Even if you dont sell anything.
It happen lot of time but not always. Its little bit random.

**Comment by cbnolok** [comment]
Do you use latest commit? Which client version? Does it happen with a specific npc? I can't reproduce it with latest commit, release/debug + VS 2015 build, 2D 4.0.11c, CC 7.0.49.62, EC 4.0.48.0.

**Comment by Tolokio** [comment]
I didnt tried commits. No crash now.   
GoodJob.
